kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
  - role: control-plane
    extraMounts:
      # Needed for CAPD
      - hostPath: /var/lib/docker
        containerPath: /var/lib/docker
      # Needed for CAPD
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
